#!/bin/bash

export GOPATH=${WORKSPACE}

#rm -rf ${WORKSPACE}/bin/*




versionfile=./internal/basic/version/version.go
cat >${versionfile} <<EOT
package version

// BuildID function
func BuildID() string {
	return ${BUILD_ID}
}

// BuildDate function
func BuildDate() string {
	return $(date '+%Y-%m-%d %H:%M:%S')
}

// GitCommit function
func GitCommit() string {
	return ${GIT_COMMIT}
}

// GitBranch function
func GitBranch() string {
	return "${GIT_BRANCH}"
}

// GitURL function
func GitURL() string {
	return "${GIT_URL}"
}

EOT

go get -d ./...
go install ./...