#!/bin/bash

REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="build"
REPOSITORY="build"
GROUPID="com.rsmaxwell.players"
NAME="players-api"
PACKAGING="zip"

GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

URL=${REPOSITORY_URL}/${REPOSITORY}/
ARTIFACTID=${JOB_NAME}-${GOARCH}-${GOOS}
FILENAME=${JOB_NAME}-${GOARCH}-${GOOS}-${BUILD_ID}.${PACKAGING}

CLASSIFIER_TEST="test"
FILENAME_TEST=${JOB_NAME}-${GOARCH}-${GOOS}-${BUILD_ID}-${CLASSIFIER_TEST}.${PACKAGING}

currentDir=$(pwd)
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

cd ${WORKSPACE}/bin
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

#****************************************************************
#* Deploy the main executable
#****************************************************************
zip ${FILENAME} players-api version.json
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mvn --batch-mode deploy:deploy-file \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${BUILD_ID} \
	-Dpackaging=${PACKAGING} \
	-Dfile=${FILENAME} \
	-DrepositoryId=${REPOSITORYID} \
	-Durl=${URL}  1>stdout.txt 2>stderr.txt

result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "----[ stdout ]--------------------------"
    cat stdout.txt
    echo "----[ stderr ]--------------------------"
    cat stderr.txt
    echo "----------------------------------------"
    exit 1
fi

#****************************************************************
#* Deploy the test utilities
#****************************************************************
zip ${FILENAME_TEST} generate-test-data version.json
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mvn --batch-mode deploy:deploy-file \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${BUILD_ID} \
	-Dclassifier=${CLASSIFIER_TEST} \
	-Dpackaging=${PACKAGING} \
	-Dfile=${FILENAME_TEST} \
	-DrepositoryId=${REPOSITORYID} \
	-Durl=${URL}  1>stdout.txt 2>stderr.txt

result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "----[ stdout ]--------------------------"
    cat stdout.txt
    echo "----[ stderr ]--------------------------"
    cat stderr.txt
    echo "----------------------------------------"
    exit 1
fi

cd ${currentDir}
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi