#!/bin/bash

REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="internal"
REPOSITORY="internal"
GROUPID="com.rsmaxwell.players-api"
NAME="players-api"
PACKAGING="zip"

GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

URL=${REPOSITORY_URL}/${REPOSITORY}/
ARTIFACTID=${JOB_NAME}-${GOARCH}-${GOOS}
FILENAME=${JOB_NAME}-${GOARCH}-${GOOS}-${BUILD_ID}.${PACKAGING}

cd ${WORKSPACE}/bin
zip ${FILENAME} *

mvn --batch-mode deploy:deploy-file \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${BUILD_ID} \
	-Dpackaging=${PACKAGING} \
	-Dfile=${FILENAME} \
	-DrepositoryId=${REPOSITORYID} \
	-Durl=${URL}
