#!/bin/bash

REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="build"
REPOSITORY="build"
GROUPID="com.rsmaxwell.players"
NAME="players-api"
PACKAGING="zip"

GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

URL=${REPOSITORY_URL}/${REPOSITORY}/
ARTIFACTID=${JOB_NAME}-${GOARCH}-${GOOS}
FILENAME=${JOB_NAME}-${GOARCH}-${GOOS}-${BUILD_ID}.${PACKAGING}

BUILD_DATE=$(date "+%Y/%m/%d %H:%M:%S")

echo '{}'   | jq --arg foo "${BUILD_ID}"   '. + {version: $foo}' > f1.json
cat f1.json | jq --arg foo "${BUILD_DATE}" '. + {buildDate: $foo}' > f2.json
cat f2.json | jq --arg foo "${GIT_COMMIT}" '. + {gitCommit: $foo}' > f3.json
cat f3.json | jq --arg foo "${GIT_BRANCH}" '. + {gitBranch: $foo}' > f4.json
cat f4.json | jq --arg foo "${GIT_URL}"    '. + {gitURL: $foo}' > version.json

pwd
ls -al
cat version.json
jq . version.json

zip ${FILENAME} ${WORKSPACE}/bin/players-api version.json
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mvn --batch-mode deploy:deploy-file \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${BUILD_ID} \
	-Dpackaging=${PACKAGING} \
	-Dfile=${FILENAME} \
	-DrepositoryId=${REPOSITORYID} \
	-Durl=${URL}  1>stdout.txt 2>stderr.txt

result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "----[ stdout ]--------------------------"
    cat stdout.txt
    echo "----[ stderr ]--------------------------"
    cat stderr.txt
    echo "----------------------------------------"
    exit 1
fi

