#!/bin/bash

#ENDPOINT="https://server.rsmaxwell.co.uk/players-api"
ENDPOINT="http://localhost:4201/players-api"

OPTIONS="--silent --cookie cookie-jar.txt --cookie-jar cookie-jar.txt --dump-header - -k"

echo "------------------------------------------------------------------"
echo "Register"

COMMAND="/users/register"

cat > data.json <<EOT
{  
    "userID": "007",
    "firstname": "James",
    "lastname": "Bond",
    "email": "james@mi6.co.uk",
    "password": "topsecret"
}
EOT
cat data.json

set -x
curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--data-binary @data.json
set +x

echo "------------------------------------------------------------------"
echo "Authenticate"

COMMAND="/users/authenticate"
USERID="007"
PASSWORD="topsecret"

set -x
curl ${OPTIONS} -X POST -u "${USERID}:${PASSWORD}" ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json"
set +x

echo "------------------------------------------------------------------"
echo "Register"

COMMAND="/users/register"

cat > data.json <<EOT
{  
    "userID": "alice",
    "firstname": "Alice",
    "lastname": "Wonderland",
    "email": "alice@abc.com",
    "password": "wonder"
}
EOT
cat data.json

set -x
curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--data-binary @data.json
set +x

echo "------------------------------------------------------------------"
echo "Update Person Role"

COMMAND="/users/role/alice"

cat > data.json <<EOT
{
    "role": "normal"
}
EOT
cat data.json

set -x
curl ${OPTIONS} -X PUT ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x

echo "------------------------------------------------------------------"
echo "Update Person Player"

COMMAND="/users/player/alice"

cat > data.json <<EOT
{
    "player": true
}
EOT
cat data.json

set -x
curl ${OPTIONS} -X PUT ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x

echo "------------------------------------------------------------------"
echo "Read Person - alice"

COMMAND="/users/alice"

set -x
curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--output output.txt 
set +x
jq . output.txt

echo "------------------------------------------------------------------"
echo "Read People"

COMMAND="/users"

cat > data.json <<EOT
{
    "filter": [
        "admin",
        "normal",
        "suspended"
    ]
}
EOT
cat data.json

set -x
curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x

echo "------------------------------------------------------------------"
echo "Logout"

COMMAND="/users/logout"

set -x
curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json"
set +x

echo "------------------------------------------------------------------"
