#!/bin/bash

ENDPOINT="https://server.rsmaxwell.co.uk/players-api"
#ENDPOINT="http://localhost:4201/players-api"


#------------------------------------------------------------------
echo "Register"

# COMMAND="/register"
# 
# cat > data.json <<EOT
# {  
#     "userID": "007",
#     "first_name": "James",
#     "last_name": "Bond",
#     "email": "james@mi6.co.uk",
#     "password": "topsecret"
# }
# EOT
# 
# set -x
# curl -k -X POST ${ENDPOINT}${COMMAND} \
# --header "Content-Type: application/json" \
# --data-binary @data.json
# set +x

#------------------------------------------------------------------
echo "Login"

COMMAND="/login"
USERID="007"
PASSWORD="topsecret"

set -x
output=$(curl --silent -k -X GET -u "${USERID}:${PASSWORD}" ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json")
set +x

token=$(echo ${output} | jq .token -r)

echo "token: ${token}"

#------------------------------------------------------------------
echo "Read People"

COMMAND="/person"

cat > data.json <<EOT
{
    "token": "${token}"
}
EOT

set -x
curl --silent -k -X GET ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x


