#!/bin/bash

#ENDPOINT="https://server.rsmaxwell.co.uk/players-api"
ENDPOINT="http://localhost:4201/players-api"


#------------------------------------------------------------------
echo "Register"

COMMAND="/register"

cat > data.json <<EOT
{  
    "userID": "007",
    "firstname": "James",
    "lastname": "Bond",
    "email": "james@mi6.co.uk",
    "password": "topsecret"
}
EOT

set -x
curl -k -X POST ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--data-binary @data.json
set +x

#------------------------------------------------------------------
echo "Login"

COMMAND="/login"
USERID="007"
PASSWORD="topsecret"

set -x
output=$(curl --silent -k -X GET -u "${USERID}:${PASSWORD}" ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json")
set +x

token=$(echo ${output} | jq .token -r)

echo "token: ${token}"




#------------------------------------------------------------------
echo "Register"

COMMAND="/register"

cat > data.json <<EOT
{  
    "userID": "alice",
    "firstname": "Alice",
    "lastname": "Wonderland",
    "email": "alice@abc.com",
    "password": "wonder"
}
EOT

set -x
curl -w "%{http_code}\n" -k -X POST ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--data-binary @data.json
set +x



#------------------------------------------------------------------
echo "Update Person"

COMMAND="/person/alice"

cat > data.json <<EOT
{
    "token": "${token}",
    "person": {
        "role": "normal"
    }
}
EOT

set -x
curl -w "%{http_code}\n" -k -X PUT ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x


#------------------------------------------------------------------
echo "Read People"

COMMAND="/person"

cat > data.json <<EOT
{
    "token": "${token}",
    "filter": [
        "admin",
        "normal",
        "suspended"
    ]
}
EOT

set -x
curl -w "%{http_code}\n" -k -X GET ${ENDPOINT}${COMMAND} \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary @data.json
set +x


